### PR TITLE
Update scan_page.dart

### PR DESCRIPTION
**Pull request by HsnU3fi**

### CODE REVIEW

**Comment by alextekartik** [comment]
Thank you!

**Comment by HsnU3fi** [comment]
🙏🙏

**Comment by lokinz** [comment]
That's great. I am using it in a PWA so was not able to escape the camera. 
I ended up re-implementing `scanQrCode` in the project and adding a floating "close" button.

**Comment by alextekartik** [comment]
Yeah appBar sometimes looks so 2017. I would be interested in having the close button as well!

**Pull request merged**
